parameters:
  artifactDropName: terraformplan
  environmentServiceNameAzureRM: ""
  variableGroupName: ""
  environmentName: ADC-DAY7-SCM-DEV
  prefix: adcday7
  env: dev

jobs:
  - job: Build
    displayName: TearDown(!) Scm Common / Infrstructure
    variables:
      - group: ${{ parameters.variableGroupName }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: "0.12.24"
      - task: TerraformTaskV1@0
        displayName: Terraform Init
        inputs:
          provider: "azurerm"
          command: "init"
          workingDirectory: "$(System.DefaultWorkingDirectory)/day7/terraform"
          backendServiceArm: ${{ parameters.environmentServiceNameAzureRM }}
          backendAzureRmResourceGroupName: $(tfresourcegroup)
          backendAzureRmStorageAccountName: $(tfstorageaccount)
          backendAzureRmContainerName: $(tfcontainer)
          backendAzureRmKey: $(tfstoragekey)
      - task: TerraformTaskV1@0
        displayName: Terraform Apply
        inputs:
          provider: "azurerm"
          command: "destroy"
          workingDirectory: "$(System.DefaultWorkingDirectory)/day7/terraform"
          commandOptions: '-auto-approve'
          environmentServiceNameAzureRM: ${{ parameters.environmentServiceNameAzureRM }}

